services:
  api_db:
    image: postgres:18
    restart: always
    environment:
      - POSTGRES_DB=${API_DB}
      - POSTGRES_USER=${API_DB_USER}
      - POSTGRES_PASSWORD=${API_DB_PASSWORD}
    ports:
      - ${API_DB_PORT}:${API_DB_PORT}
    container_name: api_db
    volumes:
      - api_postgres_db:/var/lib/postgresql/
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -p ${API_DB_PORT} -U ${API_DB_USER} -d ${API_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  test_db:
    image: postgres:18
    restart: always
    environment:
      - POSTGRES_DB=${TEST_DB}
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
    ports:
      - ${TEST_DB_PORT}:${API_DB_PORT}
    container_name: test_db
    volumes:
      - test_postgres_db:/var/lib/postgresql/
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -p ${TEST_DB_PORT} -U ${TEST_DB_USER} -d ${TEST_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - ${BROKER_PORT}:${BROKER_PORT}
      - ${BROKER_PLUGIN_PORT}:${BROKER_PLUGIN_PORT}
    environment:
      - RABBITMQ_DEFAULT_USER=${BROKER_USER}
      - RABBITMQ_DEFAULT_PASS=${BROKER_PASSWORD}
      - RABBITMQ_DEFAULT_VHOST=${BROKER_VHOST}
    container_name: rabbitmq
    healthcheck:
      test:
        ["CMD-SHELL", "rabbitmq-diagnostics -q check_running"]
      interval: 5s
      timeout: 5s
      retries: 5

  app_celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    environment:
      - WORKER_DATABASE_URL=postgresql+psycopg2://${API_DB_USER}:${API_DB_PASSWORD}@api_db:5432/${API_DB}
      - BROKER_URL=amqp://${BROKER_USER}:${BROKER_PASSWORD}@rabbitmq:5672/${BROKER_VHOST}
    command: ["celery", "-A", "app.schedules.celery_app", "worker", "-l", "info", "-P", "gevent"]
    container_name: app_celery_worker
    volumes:
      - .:/app
    depends_on:
      api_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  app_celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    environment:
      - BROKER_URL=amqp://${BROKER_USER}:${BROKER_PASSWORD}@rabbitmq:5672/${BROKER_VHOST}
    command: ["celery", "-A", "app.schedules.celery_app", "beat", "-l", "info"]
    container_name: app_celery_beat
    volumes:
      - .:/app
    depends_on:
      api_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    environment:
      - DATABASE_URL=postgresql+psycopg://${API_DB_USER}:${API_DB_PASSWORD}@api_db:5432/${API_DB}
      - TEST_DATABASE_URL=postgresql+psycopg2://${TEST_DB_USER}:${TEST_DB_PASSWORD}@test_db:5433/${TEST_DB}
      - WORKER_DATABASE_URL=postgresql+psycopg2://${API_DB_USER}:${API_DB_PASSWORD}@api_db:5432/${API_DB}
      - BROKER_URL=amqp://${BROKER_USER}:${BROKER_PASSWORD}@rabbitmq:5672/${BROKER_VHOST}
    ports:
      - ${API_PORT}:${API_PORT}
    container_name: api
    volumes:
      - .:/app
      - pytest_cache:/app/.pytest_cache
    depends_on:
      api_db:
        condition: service_healthy

volumes:
  api_postgres_db:
  test_postgres_db:
  pytest_cache: